name: Build Firmware

on: [push, pull_request]

jobs:
  build-flash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache buildroot DL
        uses: actions/cache@v3
        with:
          path: ./dl
          key: ${{ runner.os }}-flash-buildroot-dl

      - name: Build
        run: |
          bash build.sh hdzgoggle_flash_defconfig
          bash build.sh -j1 source
          bash build.sh -j4

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HDZG_OS.bin
          path: output/images/HDZG_OS.bin

  build-sdcard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache buildroot DL
        uses: actions/cache@v3
        with:
          path: ./dl
          key: ${{ runner.os }}-sdcard-buildroot-dl

      - name: Build
        run: |
          bash build.sh hdzgoggle_sdcard_defconfig
          bash build.sh -j1 source
          bash build.sh -j4

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sdcard.img
          path: output/images/sdcard.img
